services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 206206
      POSTGRES_DB: miniproject
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:206206@db:5432/miniproject"
      NEXTAUTH_SECRET: "shisisksbsha"
      NEXTAUTH_URL: "http://localhost:3000"
      ADMIN_EMAIL: "admin@gmail.com"
      ADMIN_PASSWORD: "admin123"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: 
